services:
  nginx:
    image: alfg/nginx-rtmp
    container_name: nginx_gateway
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./nginx/hls:/tmp/hls
    depends_on:
      - nest-backend
      - next-app
    networks:
      - app-network
    restart: always

  nest-backend:
    build:
      context: ./apps/nest-backend
      dockerfile: Dockerfile
    container_name: nest_backend
    working_dir: /app
    volumes:
      - ./apps/nest-backend:/app:delegated
      - nest_backend_node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    restart: always

  next-app:
    image: node:22-slim
    container_name: next_app
    working_dir: /app
    volumes:
      - ./apps/next-app:/app
      - next_app_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - nest-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://nest-backend:4000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
volumes:
  nest_backend_node_modules:
  next_app_node_modules:
