services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nest-backend
      - next-app
    networks:
      - app-network
    restart: always

  nest-backend:
    build:
      context: ./apps/nest-backend
      dockerfile: Dockerfile
    container_name: nest_backend
    working_dir: /app
    volumes:
      - ./apps/nest-backend:/app:delegated
      - nest_backend_node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      # - DATABASE_URL=mongodb://mongo:27017/mydatabase
    # depends_on:
    #   - mongo
    networks:
      - app-network
    restart: always

  # mongo:
  #   image: mongo:latest
  #   container_name: mongo_db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - app-network
  #   restart: always

  next-app:
    image: node:22-slim
    container_name: next_app
    working_dir: /app
    volumes:
      - ./apps/next-app:/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - nest-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://nest-backend:4000
    networks:
      - app-network
    restart: always

  electron-app:
    image: node:22-slim
    container_name: electron_app
    depends_on:
      - nest-backend
    working_dir: /app
    volumes:
      - ./apps/electron-app:/app
    command: sh -c "npm install --include=dev && npm start"

networks:
  app-network:
   driver: bridge
volumes:
  # mongo_data:
  nest_backend_node_modules: