import type { Metadata } from 'next'
import { Geist_Mono } from 'next/font/google'
import { cookies } from 'next/headers'

import Layout from '@/components/layout'

import { cookiesConstant } from '@/config/cookies.constants'

import './globals.css'
import { ICurrentUser } from '@/interfaces/user/user.interface'

const font = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const getCurrentUser = async (): Promise<ICurrentUser> => {
  const cookieStore = await cookies()
  const cookie = cookieStore.get(cookiesConstant.currentUser)
  return cookie ? JSON.parse(cookie.value) : { authorized: false, user: null }
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const currentUser = await getCurrentUser()

  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${font.variable} antialiased`}>
        <Layout currentUser={currentUser}>{children}</Layout>
      </body>
    </html>
  )
}
